# Generated by Django 4.1.9 on 2023-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('run_id', models.IntegerField(blank=True, null=True)),
                ('app_id', models.CharField(blank=True, default=1029384234, max_length=10, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('app_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('app_flavor', models.CharField(default='None', max_length=20)),
                ('app_size', models.BigIntegerField(blank=True, null=True)),
                ('app_type', models.CharField(blank=True, max_length=20, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=300, null=True)),
                ('distribution_kind', models.CharField(blank=True, max_length=20, null=True)),
                ('user_rating_value', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('user_rating_count', models.IntegerField(blank=True, null=True)),
                ('user_rating_label', models.CharField(blank=True, max_length=20, null=True)),
                ('app_store_position', models.IntegerField(blank=True, null=True)),
                ('app_store_genre_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_store_genre_code', models.IntegerField(blank=True, null=True)),
                ('app_store_chart', models.CharField(blank=True, max_length=30, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('version_release_date', models.CharField(blank=True, max_length=40, null=True)),
                ('release_date', models.CharField(blank=True, max_length=40, null=True)),
                ('privacy_policy_url', models.CharField(blank=True, max_length=300, null=True)),
                ('has_in_app_purchases', models.SmallIntegerField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, max_length=300, null=True)),
                ('price_formatted', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('insert_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='App_Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data_Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Data_Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privacy_Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('privacy_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'privacy_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'purpose',
                'managed': False,
            },
        ),
    ]
